version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: restaurant-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: restaurant
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - restaurant-network

  backend:
    build: ./restaurant-backend
    container_name: restaurant-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/restaurant?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      CORS_ORIGIN: http://localhost:3000,http://localhost:3001
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - restaurant-network

  frontend:
    build: ./restaurant-frontend
    container_name: restaurant-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    networks:
      - restaurant-network

  user-app:
    build: ./restaurant-user-app
    container_name: restaurant-user-app
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    networks:
      - restaurant-network

volumes:
  mongodb_data:

networks:
  restaurant-network:
    driver: bridge