services:
  - type: web
    name: restaurant-user-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false # Set this in Render dashboard